####
GET http://localhost:3000/todo

####
POST http://localhost:3000/todo HTTP/1.1
content-type: application/json

{
    "title": "Title 2",
    "subtitle": "This is a random subtitle",
    "body": "Lorem Ipsum Dolor Amet to edit"
}

####
GET http://localhost:3000/todo/600dadd5be856e08f22ad00f

####

PATCH http://localhost:3000/todo/600dadd5be856e08f22ad00f
content-type: application/json

{
    "subtitle": "This was edited again and again and again..."
}

####
DELETE http://localhost:3000/todo/600ddd7fb1830f17cb127fbb

####
DELETE http://localhost:3000/todo